import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { calculateFeasibility, calculatePackingListTotals } from "./calculations";
import { FeasibilityStudy, PackingList, Shipment } from "./storage";
import { ar } from "./arabicReshaper";

// ─── Font loading ─────────────────────────────────────────────────────────────

let cairoRegB64: string | null = null;
let cairoBoldB64: string | null = null;

async function ttfToB64(url: string): Promise<string> {
  const resp = await fetch(url);
  if (!resp.ok) throw new Error(`Font fetch failed: ${url}`);
  const buf = await resp.arrayBuffer();
  const u8 = new Uint8Array(buf);
  let bin = "";
  const CHUNK = 8192;
  for (let i = 0; i < u8.length; i += CHUNK)
    bin += String.fromCharCode(...u8.subarray(i, i + CHUNK));
  return btoa(bin);
}

async function loadCairo(doc: jsPDF): Promise<void> {
  if (!cairoRegB64)  cairoRegB64  = await ttfToB64("/fonts/Cairo-Regular.ttf");
  if (!cairoBoldB64) cairoBoldB64 = await ttfToB64("/fonts/Cairo-Bold.ttf");
  doc.addFileToVFS("Cairo-Regular.ttf", cairoRegB64);
  doc.addFont("Cairo-Regular.ttf", "Cairo", "normal");
  doc.addFileToVFS("Cairo-Bold.ttf", cairoBoldB64);
  doc.addFont("Cairo-Bold.ttf", "Cairo", "bold");
  doc.setFont("Cairo", "normal");
}

// ─── Shared helpers ───────────────────────────────────────────────────────────

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

function todayStr() {
  return new Date().toLocaleDateString("en-GB");
}

/** Always use Western digits in PDFs to avoid Arabic-Indic numeral encoding issues */
function fmt(num: number, decimals = 2): string {
  return num.toLocaleString("en-US", {
    maximumFractionDigits: decimals,
    minimumFractionDigits: decimals,
  });
}

function safeSheetName(raw: string, taken: string[]): string {
  const clean = raw.replace(/[\/\\?*\[\]:]/g, "").trim().slice(0, 28) || "Sheet";
  let name = clean; let i = 2;
  while (taken.includes(name)) name = `${clean.slice(0, 25)} (${i++})`;
  return name;
}

// jsPDF-autotable style presets using Cairo font
const BASE_STYLE = { font: "Cairo", fontSize: 9, cellPadding: 3 };
const HEAD_DARK   = { fillColor: [15, 23, 42]  as [number,number,number], textColor: 255, font: "Cairo", fontStyle: "bold" as const, fontSize: 9 };
const HEAD_NAVY   = { fillColor: [30, 41, 59]  as [number,number,number], textColor: 255, font: "Cairo", fontStyle: "bold" as const, fontSize: 9 };
const HEAD_BLUE   = { fillColor: [30, 64, 175] as [number,number,number], textColor: 255, font: "Cairo", fontStyle: "bold" as const, fontSize: 9 };
const ALT_ROW     = { fillColor: [245, 247, 250] as [number,number,number] };

// Draw a standard header bar and return the Y position below it
function drawHeader(
  doc: jsPDF,
  title: string,
  subtitle: string,
  barH = 28,
  fillColor: [number,number,number] = [15, 23, 42],
): number {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(...fillColor);
  doc.rect(0, 0, pageW, barH, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("Cairo", "bold"); doc.setFontSize(15);
  doc.text(title, pageW / 2, barH * 0.42, { align: "center" });
  doc.setFont("Cairo", "normal"); doc.setFontSize(9);
  doc.text(subtitle, pageW / 2, barH * 0.78, { align: "center" });
  doc.setTextColor(30, 30, 30);
  return barH + 4;
}

function drawFooter(doc: jsPDF) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFont("Cairo", "normal"); doc.setFontSize(7.5);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by China Import Tracker  |  ${ar("مستورد الصين")}  |  ${todayStr()}`,
    pageW / 2, pageH - 5, { align: "center" }
  );
}

// ─── PDF – Feasibility Study ──────────────────────────────────────────────────

export async function exportStudyPDF(study: FeasibilityStudy) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  await loadCairo(doc);
  const calc = calculateFeasibility(study);
  const pageW = doc.internal.pageSize.getWidth();

  let y = drawHeader(
    doc,
    "Feasibility Study Report",
    `China Import Tracker  |  ${ar("مستورد الصين")}`,
  );

  // Product name + meta
  doc.setFont("Cairo", "bold"); doc.setFontSize(12);
  doc.text(ar(study.productName), pageW - 14, y + 8, { align: "right" });
  doc.setFont("Cairo", "normal"); doc.setFontSize(8.5);
  doc.setTextColor(100, 100, 100);
  doc.text(
    `Date: ${todayStr()}   |   Currency: ${study.currency}   |   Qty: ${study.quantity.toLocaleString("en-US")} units`,
    14, y + 15
  );
  doc.setTextColor(30, 30, 30);

  autoTable(doc, {
    startY: y + 20,
    head: [["Input Parameter", "Value"]],
    body: [
      ["Factory Unit Price",              `${fmt(study.factoryPrice)} ${study.currency}`],
      ["Quantity",                        `${study.quantity.toLocaleString("en-US")} units`],
      ["Units per Carton",                `${study.unitsPerCarton}`],
      ["Carton Dimensions (cm)",          `${study.cartonLength} × ${study.cartonWidth} × ${study.cartonHeight}`],
      ["Gross Weight / Carton (kg)",      `${study.grossWeight ?? "—"}`],
      ["Domestic Shipping China (RMB)",   `${fmt(study.domesticShippingRMB)}`],
      ["Sea / Air Freight (SAR)",         `${fmt(study.freightCostSAR)}`],
      ["Custom Duty %",                   `${study.customDutyPct}%`],
      ["VAT %",                           `${study.vatPct}%`],
      ["Customs Clearance (SAR)",         `${fmt(study.clearanceFeeSAR)}`],
      ["Saudi Internal Logistics (SAR)",  `${fmt(study.localLogisticsSAR)}`],
      ["SABER / SFDA Cert. (SAR)",        `${fmt(study.certificationFeeSAR)}`],
      ["Target Selling Price / Unit (SAR)", `${fmt(study.targetSellingPrice)}`],
    ],
    theme: "striped",
    headStyles: HEAD_DARK,
    alternateRowStyles: ALT_ROW,
    styles: { ...BASE_STYLE },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 90 }, 1: { halign: "right" } },
  });

  const afterInputs = (doc as any).lastAutoTable.finalY + 6;

  doc.setFont("Cairo", "bold"); doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("Calculated Results", 14, afterInputs);

  const profitColor: [number,number,number] = calc.netProfitSAR >= 0 ? [22, 163, 74] : [239, 68, 68];
  const riskColor:   [number,number,number] =
    calc.riskScore <= 3 ? [34, 197, 94] : calc.riskScore <= 6 ? [234, 179, 8] : [239, 68, 68];

  autoTable(doc, {
    startY: afterInputs + 4,
    head: [["Result Metric", "Value"]],
    body: [
      ["Total Landed Cost (SAR)",              fmt(calc.totalLandedCostSAR)],
      ["Cost per Unit Landed (SAR)",           fmt(calc.costPerUnitLandedSAR)],
      ["Recommended Min. Selling Price (SAR)", fmt(calc.recommendedMinPriceSAR)],
      ["Net Profit — Total (SAR)",             fmt(calc.netProfitSAR)],
      ["Net Profit per Unit (SAR)",            fmt(calc.netProfitPerUnitSAR)],
      ["Net Profit Margin %",                  `${fmt(calc.netProfitMarginPct)}%`],
      ["ROI %",                                `${fmt(calc.roiPct)}%`],
      ["Total Volume (CBM)",                   fmt(calc.totalCBM, 3)],
      ["Total Cartons",                        `${calc.totalCartons}`],
      ["Risk Score",                           `${calc.riskScore} / 10`],
    ],
    theme: "grid",
    headStyles: HEAD_NAVY,
    styles: { ...BASE_STYLE, fontSize: 10, cellPadding: 3.5 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 90 }, 1: { halign: "right" } },
    didDrawCell: (data: any) => {
      if (data.section !== "body") return;
      if (data.column.index !== 1) return;
      if (data.row.index === 3 || data.row.index === 4) doc.setTextColor(...profitColor);
      else if (data.row.index === 9) doc.setTextColor(...riskColor);
      else doc.setTextColor(30, 30, 30);
    },
  });

  drawFooter(doc);
  doc.save(`Study_${study.productName.replace(/\s+/g, "_")}_${todayStr().replace(/\//g, "-")}.pdf`);
}

// ─── Excel – Feasibility Study ────────────────────────────────────────────────

export function exportStudyExcel(study: FeasibilityStudy) {
  const calc = calculateFeasibility(study);
  const rows: any[][] = [
    ["بيانات المدخلات", ""],
    ["اسم المنتج", study.productName],
    ["العملة", study.currency],
    ["سعر المصنع لكل وحدة", study.factoryPrice],
    ["الكمية المطلوبة", study.quantity],
    ["قطع بالكرتونة", study.unitsPerCarton],
    ["طول الكرتونة (سم)", study.cartonLength],
    ["عرض الكرتونة (سم)", study.cartonWidth],
    ["ارتفاع الكرتونة (سم)", study.cartonHeight],
    ["الشحن الداخلي في الصين (يوان)", study.domesticShippingRMB],
    ["تكلفة الشحن البحري/الجوي (ر.س)", study.freightCostSAR],
    ["الرسوم الجمركية %", study.customDutyPct],
    ["ضريبة القيمة المضافة %", study.vatPct],
    ["أجور التخليص الجمركي (ر.س)", study.clearanceFeeSAR],
    ["الشحن الداخلي للمستودع (ر.س)", study.localLogisticsSAR],
    ["رسوم الشهادات سابر/SFDA (ر.س)", study.certificationFeeSAR],
    ["سعر البيع المستهدف لكل وحدة (ر.س)", study.targetSellingPrice],
    ["", ""],
    ["نتائج دراسة الجدوى", ""],
    ["إجمالي التكلفة واصل المستودع (ر.س)", calc.totalLandedCostSAR],
    ["التكلفة لكل وحدة واصل (ر.س)", calc.costPerUnitLandedSAR],
    ["السعر الأدنى المقترح للبيع (ر.س)", calc.recommendedMinPriceSAR],
    ["الربح الإجمالي (ر.س)", calc.netProfitSAR],
    ["الربح لكل وحدة (ر.س)", calc.netProfitPerUnitSAR],
    ["هامش الربح الصافي %", calc.netProfitMarginPct],
    ["العائد على الاستثمار ROI %", calc.roiPct],
    ["إجمالي الحجم CBM", calc.totalCBM],
    ["إجمالي عدد الكراتين", calc.totalCartons],
    ["نسبة المخاطرة (من 10)", calc.riskScore],
    ["", ""],
    ["تاريخ الإنشاء", todayStr()],
  ];
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws["!cols"] = [{ wch: 38 }, { wch: 20 }];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "دراسة الجدوى");
  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  triggerDownload(
    new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `Study_${study.productName}_${todayStr().replace(/\//g, "-")}.xlsx`
  );
}

// ─── PDF – Multi Feasibility Studies ─────────────────────────────────────────

export async function exportMultiStudyPDF(studies: FeasibilityStudy[]) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  await loadCairo(doc);
  const pageW = doc.internal.pageSize.getWidth();

  let y = drawHeader(
    doc,
    "Combined Feasibility Report",
    `China Import Tracker  |  ${ar("مستورد الصين")}  |  Studies: ${studies.length}  |  ${todayStr()}`,
  );

  doc.setFont("Cairo", "bold"); doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("Summary", 14, y + 4);

  autoTable(doc, {
    startY: y + 8,
    head: [["#", "Product", "Qty", "Unit Cost (SAR)", "Net Profit (SAR)", "Margin %", "ROI %", "Risk"]],
    body: studies.map((s, i) => {
      const c = calculateFeasibility(s);
      return [
        i + 1,
        ar(s.productName),
        s.quantity.toLocaleString("en-US"),
        fmt(c.costPerUnitLandedSAR),
        fmt(c.netProfitSAR),
        `${fmt(c.netProfitMarginPct)}%`,
        `${fmt(c.roiPct)}%`,
        `${c.riskScore}/10`,
      ];
    }),
    theme: "striped",
    headStyles: { ...HEAD_DARK, fontSize: 8 },
    alternateRowStyles: ALT_ROW,
    styles: { ...BASE_STYLE, fontSize: 8, cellPadding: 2.5 },
    columnStyles: { 1: { cellWidth: 50, halign: "right" } },
  });

  // One page per study
  studies.forEach((study, idx) => {
    const calc = calculateFeasibility(study);
    doc.addPage();

    doc.setFillColor(30, 64, 175);
    doc.rect(0, 0, pageW, 22, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("Cairo", "bold"); doc.setFontSize(11);
    doc.text(`[${idx + 1}]  ${ar(study.productName)}`, pageW / 2, 14, { align: "center" });
    doc.setTextColor(30, 30, 30);

    autoTable(doc, {
      startY: 28,
      head: [["Metric", "Value"]],
      body: [
        ["Total Landed Cost (SAR)",              fmt(calc.totalLandedCostSAR)],
        ["Cost / Unit (SAR)",                    fmt(calc.costPerUnitLandedSAR)],
        ["Min. Selling Price (SAR)",             fmt(calc.recommendedMinPriceSAR)],
        ["Net Profit — Total (SAR)",             fmt(calc.netProfitSAR)],
        ["Net Profit / Unit (SAR)",              fmt(calc.netProfitPerUnitSAR)],
        ["Profit Margin %",                      `${fmt(calc.netProfitMarginPct)}%`],
        ["ROI %",                                `${fmt(calc.roiPct)}%`],
        ["Total Volume (CBM)",                   fmt(calc.totalCBM, 3)],
        ["Total Cartons",                        `${calc.totalCartons}`],
        ["Risk Score",                           `${calc.riskScore} / 10`],
      ],
      theme: "grid",
      headStyles: HEAD_NAVY,
      styles: { ...BASE_STYLE, fontSize: 9.5, cellPadding: 3.2 },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 85 }, 1: { halign: "right" } },
    });

    drawFooter(doc);
  });

  doc.save(`CombinedStudies_${todayStr().replace(/\//g, "-")}.pdf`);
}

// ─── Excel – Multi Feasibility Studies ───────────────────────────────────────

export function exportMultiStudyExcel(studies: FeasibilityStudy[]) {
  const wb = XLSX.utils.book_new();
  const taken: string[] = [];

  const summaryRows: any[][] = [
    ["Combined Feasibility Report  –  تقرير دراسات الجدوى المجمّع"],
    ["Date:", todayStr(), "", "Studies:", studies.length],
    [],
    ["#", "اسم المنتج", "الكمية", "تكلفة الوحدة (ر.س)", "السعر المقترح (ر.س)",
     "الربح الإجمالي (ر.س)", "الربح/وحدة (ر.س)", "هامش الربح %", "ROI %", "مخاطرة/10"],
    ...studies.map((s, i) => {
      const c = calculateFeasibility(s);
      return [i + 1, s.productName, s.quantity,
        +c.costPerUnitLandedSAR.toFixed(2), +c.recommendedMinPriceSAR.toFixed(2),
        +c.netProfitSAR.toFixed(2), +c.netProfitPerUnitSAR.toFixed(2),
        +c.netProfitMarginPct.toFixed(2), +c.roiPct.toFixed(2), c.riskScore];
    }),
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  wsSummary["!cols"] = [
    { wch: 5 }, { wch: 30 }, { wch: 10 }, { wch: 18 }, { wch: 18 },
    { wch: 20 }, { wch: 18 }, { wch: 14 }, { wch: 10 }, { wch: 10 },
  ];
  const sName = safeSheetName("ملخص", taken); taken.push(sName);
  XLSX.utils.book_append_sheet(wb, wsSummary, sName);

  studies.forEach((study) => {
    const calc = calculateFeasibility(study);
    const rows: any[][] = [
      ["Feasibility Study  –  دراسة الجدوى"],
      ["Product:", study.productName], ["Date:", todayStr()], [],
      ["البند", "القيمة"],
      ["العملة", study.currency],
      ["سعر المصنع للوحدة", study.factoryPrice],
      ["الكمية", study.quantity],
      ["إجمالي التكلفة الواصلة (ر.س)", +calc.totalLandedCostSAR.toFixed(2)],
      ["التكلفة للوحدة (ر.س)", +calc.costPerUnitLandedSAR.toFixed(2)],
      ["السعر المقترح للبيع (ر.س)", +calc.recommendedMinPriceSAR.toFixed(2)],
      ["سعر البيع المستهدف (ر.س)", study.targetSellingPrice],
      ["الربح الإجمالي (ر.س)", +calc.netProfitSAR.toFixed(2)],
      ["الربح للوحدة (ر.س)", +calc.netProfitPerUnitSAR.toFixed(2)],
      ["هامش الربح %", +calc.netProfitMarginPct.toFixed(2)],
      ["ROI %", +calc.roiPct.toFixed(2)],
      ["إجمالي CBM", +calc.totalCBM.toFixed(3)],
      ["إجمالي الكراتين", calc.totalCartons],
      ["نسبة المخاطرة (من 10)", calc.riskScore],
    ];
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws["!cols"] = [{ wch: 32 }, { wch: 20 }];
    const shName = safeSheetName(study.productName, taken); taken.push(shName);
    XLSX.utils.book_append_sheet(wb, ws, shName);
  });

  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  triggerDownload(
    new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `CombinedStudies_${todayStr().replace(/\//g, "-")}.xlsx`
  );
}

// ─── PDF – Packing List ───────────────────────────────────────────────────────

export async function exportPackingListPDF(list: PackingList) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  await loadCairo(doc);
  const totals = calculatePackingListTotals(list.items);
  const pageW = doc.internal.pageSize.getWidth();

  const y = drawHeader(
    doc,
    "PACKING LIST",
    `China Import Tracker  |  ${ar("بيان التعبئة")}`,
  );

  // Meta block
  const labelX = 14, valueX = 58;
  const metaY = y + 4;
  doc.setFont("Cairo", "bold"); doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  [["Supplier:", list.supplierName], ["B/L No:", list.billOfLading],
   ["Description:", list.goodsDescription], ["Date:", todayStr()]].forEach(([lbl, val], i) => {
    doc.text(lbl, labelX, metaY + i * 6);
    doc.setFont("Cairo", "normal");
    doc.text(ar(val), pageW - 14, metaY + i * 6, { align: "right" });
    doc.setFont("Cairo", "bold");
  });
  doc.setTextColor(30, 30, 30);

  autoTable(doc, {
    startY: metaY + 28,
    head: [["#", "Product", "Cartons", "Units/Ctn", "NW/Ctn (kg)", "GW/Ctn (kg)",
            "L×W×H (cm)", "CBM/Ctn", "Unit Value (USD)", "Total Value (USD)"]],
    body: [
      ...list.items.map((item, i) => {
        const cbm = (item.length * item.width * item.height) / 1_000_000;
        const totalValue = item.unitValueUSD * item.unitsPerCarton * item.cartonsCount;
        return [
          i + 1, ar(item.productName), item.cartonsCount, item.unitsPerCarton,
          item.netWeightPerCarton, item.grossWeightPerCarton,
          `${item.length}×${item.width}×${item.height}`,
          cbm.toFixed(3), item.unitValueUSD.toFixed(2), totalValue.toFixed(2),
        ];
      }),
      [
        { content: "TOTAL", colSpan: 2, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
        { content: totals.totalCartons, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
        { content: "", styles: { fillColor: [15,23,42] } },
        { content: `${totals.totalNetWeight.toFixed(2)} kg`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
        { content: `${totals.totalGrossWeight.toFixed(2)} kg`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
        { content: "", styles: { fillColor: [15,23,42] } },
        { content: `${totals.totalCBM.toFixed(3)} m³`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
        { content: "", styles: { fillColor: [15,23,42] } },
        { content: `$ ${totals.totalValueUSD.toFixed(2)}`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
      ],
    ],
    theme: "striped",
    headStyles: { ...HEAD_BLUE, fontSize: 8.5 },
    alternateRowStyles: ALT_ROW,
    styles: { ...BASE_STYLE, fontSize: 8, cellPadding: 2.5, halign: "center" },
    columnStyles: { 1: { halign: "right", cellWidth: 40 } },
  });

  drawFooter(doc);
  doc.save(`PackingList_${list.billOfLading}_${todayStr().replace(/\//g, "-")}.pdf`);
}

// ─── Excel – Packing List ─────────────────────────────────────────────────────

export function exportPackingListExcel(list: PackingList) {
  const totals = calculatePackingListTotals(list.items);
  const headerRows: any[][] = [
    ["Packing List  –  بيان التعبئة", "", "", "", "", "", "", "", "", ""],
    ["Supplier:", list.supplierName, "", "", "", "", "", "", "", ""],
    ["B/L No:", list.billOfLading, "", "", "", "", "", "", "", ""],
    ["Description:", list.goodsDescription, "", "", "", "", "", "", "", ""],
    ["Date:", todayStr(), "", "", "", "", "", "", "", ""],
    ["", "", "", "", "", "", "", "", "", ""],
    ["#", "المنتج / Product", "عدد الكراتين", "قطع/كرتون", "وزن صافي/كرتون (كغ)",
     "وزن إجمالي/كرتون (كغ)", "الطول (سم)", "العرض (سم)", "الارتفاع (سم)", "القيمة لكل وحدة (USD)"],
    ...list.items.map((item, i) => [
      i + 1, item.productName, item.cartonsCount, item.unitsPerCarton,
      item.netWeightPerCarton, item.grossWeightPerCarton,
      item.length, item.width, item.height, item.unitValueUSD,
    ]),
    ["", "", "", "", "", "", "", "", "", ""],
    ["الإجماليات", "", totals.totalCartons, "",
     +totals.totalNetWeight.toFixed(2), +totals.totalGrossWeight.toFixed(2),
     "", "", "", +totals.totalValueUSD.toFixed(2)],
    ["", "", "", "", "", "", "", "", "", ""],
    ["Total CBM:", +totals.totalCBM.toFixed(3), "", "", "", "", "", "", "", ""],
  ];
  const ws = XLSX.utils.aoa_to_sheet(headerRows);
  ws["!cols"] = [
    { wch: 6 }, { wch: 30 }, { wch: 14 }, { wch: 10 },
    { wch: 20 }, { wch: 22 }, { wch: 12 }, { wch: 12 }, { wch: 14 }, { wch: 20 },
  ];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Packing List");
  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  triggerDownload(
    new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `PackingList_${list.billOfLading}_${todayStr().replace(/\//g, "-")}.xlsx`
  );
}

// ─── PDF – Multi Packing List ─────────────────────────────────────────────────

export async function exportMultiPackingListPDF(lists: PackingList[]) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  await loadCairo(doc);
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  let y = drawHeader(
    doc,
    "Combined Packing List Report",
    `China Import Tracker  |  ${ar("بيانات التعبئة المجمّعة")}  |  Shipments: ${lists.length}  |  ${todayStr()}`,
    32,
  );

  for (const [idx, list] of lists.entries()) {
    const totals = calculatePackingListTotals(list.items);
    if (y > pageH - 60) { doc.addPage(); y = 10; }

    doc.setFillColor(30, 64, 175);
    doc.rect(0, y, pageW, 8, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("Cairo", "bold"); doc.setFontSize(8.5);
    doc.text(
      `[${idx + 1}]  ${ar(list.supplierName)}   |   B/L: ${list.billOfLading}   |   ${ar(list.goodsDescription)}`,
      6, y + 5.5
    );
    doc.setTextColor(30, 30, 30);
    y += 10;

    autoTable(doc, {
      startY: y,
      head: [["#", "Product", "Cartons", "Units/Ctn", "NW/Ctn kg", "GW/Ctn kg",
              "L×W×H cm", "CBM/Ctn", "Unit USD", "Total USD"]],
      body: [
        ...list.items.map((item, i) => {
          const cbm = (item.length * item.width * item.height) / 1_000_000;
          const totalValue = item.unitValueUSD * item.unitsPerCarton * item.cartonsCount;
          return [
            i + 1, ar(item.productName), item.cartonsCount, item.unitsPerCarton,
            item.netWeightPerCarton, item.grossWeightPerCarton,
            `${item.length}×${item.width}×${item.height}`,
            cbm.toFixed(3), item.unitValueUSD.toFixed(2), totalValue.toFixed(2),
          ];
        }),
        [
          { content: "SUB-TOTAL", colSpan: 2, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
          { content: totals.totalCartons, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
          { content: "", styles: { fillColor: [15,23,42] } },
          { content: `${totals.totalNetWeight.toFixed(2)} kg`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
          { content: `${totals.totalGrossWeight.toFixed(2)} kg`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
          { content: "", styles: { fillColor: [15,23,42] } },
          { content: `${totals.totalCBM.toFixed(3)} m³`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
          { content: "", styles: { fillColor: [15,23,42] } },
          { content: `$ ${totals.totalValueUSD.toFixed(2)}`, styles: { fontStyle: "bold", fillColor: [15,23,42], textColor: 255, font: "Cairo" } },
        ],
      ],
      theme: "striped",
      headStyles: { ...HEAD_BLUE, fontSize: 7.5 },
      alternateRowStyles: ALT_ROW,
      styles: { ...BASE_STYLE, fontSize: 7.5, cellPadding: 2, halign: "center" },
      columnStyles: { 1: { halign: "right", cellWidth: 38 } },
      margin: { left: 6, right: 6 },
    });

    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // Grand totals bar
  const grandCartons = lists.reduce((s, l) => s + calculatePackingListTotals(l.items).totalCartons, 0);
  const grandCBM    = lists.reduce((s, l) => s + calculatePackingListTotals(l.items).totalCBM, 0);
  const grandGW     = lists.reduce((s, l) => s + calculatePackingListTotals(l.items).totalGrossWeight, 0);
  const grandUSD    = lists.reduce((s, l) => s + calculatePackingListTotals(l.items).totalValueUSD, 0);

  if (y > pageH - 25) { doc.addPage(); y = 10; }
  doc.setFillColor(245, 197, 24);
  doc.rect(6, y, pageW - 12, 12, "F");
  doc.setTextColor(15, 23, 42);
  doc.setFont("Cairo", "bold"); doc.setFontSize(8.5);
  doc.text(
    `GRAND TOTAL  —  Shipments: ${lists.length}  |  Cartons: ${grandCartons}  |  ` +
    `CBM: ${grandCBM.toFixed(3)} m³  |  GW: ${grandGW.toFixed(2)} kg  |  Value: $${grandUSD.toFixed(2)}`,
    pageW / 2, y + 7.5, { align: "center" }
  );

  drawFooter(doc);
  doc.save(`CombinedPackingList_${todayStr().replace(/\//g, "-")}.pdf`);
}

// ─── Excel – Multi Packing List ───────────────────────────────────────────────

export function exportMultiPackingListExcel(lists: PackingList[]) {
  const wb = XLSX.utils.book_new();
  const taken: string[] = [];

  const summaryRows: any[][] = [
    ["Combined Packing List Report  –  تقرير بيانات التعبئة المجمّع"],
    ["Date:", todayStr()], ["Shipments:", lists.length], [],
    ["#", "المورد / Supplier", "رقم البوليصة / B/L", "وصف البضاعة", "عدد الأصناف",
     "إجمالي الكراتين", "CBM (م³)", "الوزن الإجمالي GW (كج)", "القيمة الإجمالية USD"],
  ];

  let grandCartons = 0, grandCBM = 0, grandGW = 0, grandUSD = 0;
  lists.forEach((list, i) => {
    const t = calculatePackingListTotals(list.items);
    grandCartons += t.totalCartons; grandCBM += t.totalCBM;
    grandGW += t.totalGrossWeight; grandUSD += t.totalValueUSD;
    summaryRows.push([i + 1, list.supplierName, list.billOfLading, list.goodsDescription,
      list.items.length, t.totalCartons, +t.totalCBM.toFixed(3), +t.totalGrossWeight.toFixed(2), +t.totalValueUSD.toFixed(2)]);
  });
  summaryRows.push([]);
  summaryRows.push(["الإجمالي الكلي", "", "", "", "", grandCartons, +grandCBM.toFixed(3), +grandGW.toFixed(2), +grandUSD.toFixed(2)]);

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  wsSummary["!cols"] = [{ wch: 5 }, { wch: 25 }, { wch: 18 }, { wch: 22 },
    { wch: 12 }, { wch: 15 }, { wch: 16 }, { wch: 18 }, { wch: 18 }];
  const sName = safeSheetName("Summary", taken); taken.push(sName);
  XLSX.utils.book_append_sheet(wb, wsSummary, sName);

  lists.forEach((list) => {
    const t = calculatePackingListTotals(list.items);
    const rows: any[][] = [
      ["Packing List  –  بيان التعبئة"],
      ["Supplier:", list.supplierName], ["B/L:", list.billOfLading],
      ["Description:", list.goodsDescription], ["Date:", todayStr()], [],
      ["#", "المنتج", "الكراتين", "قطع/كرتون", "NW/كرتون كج", "GW/كرتون كج",
       "طول سم", "عرض سم", "ارتفاع سم", "قيمة الوحدة USD", "القيمة الإجمالية USD"],
      ...list.items.map((item, i) => {
        const totalValue = item.unitValueUSD * item.unitsPerCarton * item.cartonsCount;
        return [i + 1, item.productName, item.cartonsCount, item.unitsPerCarton,
          item.netWeightPerCarton, item.grossWeightPerCarton,
          item.length, item.width, item.height, item.unitValueUSD, +totalValue.toFixed(2)];
      }),
      [],
      ["Totals", "", t.totalCartons, "", +t.totalNetWeight.toFixed(2), +t.totalGrossWeight.toFixed(2),
       "", "", "", "", +t.totalValueUSD.toFixed(2)],
      ["Total CBM:", +t.totalCBM.toFixed(3)],
    ];
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws["!cols"] = [{ wch: 5 }, { wch: 28 }, { wch: 12 }, { wch: 12 },
      { wch: 14 }, { wch: 14 }, { wch: 10 }, { wch: 10 }, { wch: 12 }, { wch: 16 }, { wch: 16 }];
    const shName = safeSheetName(list.billOfLading || list.supplierName, taken); taken.push(shName);
    XLSX.utils.book_append_sheet(wb, ws, shName);
  });

  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  triggerDownload(
    new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `CombinedPackingList_${todayStr().replace(/\//g, "-")}.xlsx`
  );
}

// ─── PDF – Shipments Tracker ──────────────────────────────────────────────────

export async function exportShipmentsPDF(shipments: Shipment[]) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  await loadCairo(doc);
  const pageW = doc.internal.pageSize.getWidth();

  const stages = [
    ar("تم الشراء"),
    ar("في مستودع الصين"),
    ar("في البحر / الجو"),
    ar("التخليص الجمركي"),
    ar("واصل للمستودع"),
  ];
  const stagesRaw = ["تم الشراء", "في مستودع الصين", "في البحر / الجو", "التخليص الجمركي", "واصل للمستودع"];

  let y = drawHeader(
    doc,
    "Shipments Tracker Report",
    `China Import Tracker  |  ${ar("متابعة الشحنات")}  |  Total: ${shipments.length} shipments  |  ${todayStr()}`,
  );

  doc.setFont("Cairo", "bold"); doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("Stage Summary:", 14, y + 4);

  autoTable(doc, {
    startY: y + 8,
    head: [["Stage", "Count"]],
    body: stagesRaw.map((s, i) => [stages[i], shipments.filter(sh => sh.stage === s).length]),
    theme: "striped",
    headStyles: { ...HEAD_NAVY, fontSize: 9 },
    alternateRowStyles: ALT_ROW,
    styles: { ...BASE_STYLE, fontSize: 9, cellPadding: 2.5 },
    tableWidth: 110,
    columnStyles: { 0: { halign: "right" }, 1: { halign: "center", cellWidth: 20 } },
  });

  const afterSummary = (doc as any).lastAutoTable.finalY + 6;
  doc.setFont("Cairo", "bold"); doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("All Shipments:", 14, afterSummary);

  autoTable(doc, {
    startY: afterSummary + 4,
    head: [["#", "Shipment Name", "Product", "Supplier", "Container No.", "Stage", "Last Update", "Notes"]],
    body: shipments.map((s, i) => [
      i + 1,
      ar(s.name),
      ar(s.productName),
      ar(s.supplier),
      s.containerNumber || "—",
      ar(s.stage),
      new Date(s.updatedAt).toLocaleDateString("en-GB"),
      s.notes.length,
    ]),
    theme: "striped",
    headStyles: { ...HEAD_BLUE, fontSize: 8 },
    alternateRowStyles: ALT_ROW,
    styles: { ...BASE_STYLE, fontSize: 8, cellPadding: 2.5 },
    columnStyles: {
      1: { cellWidth: 38, halign: "right" },
      2: { cellWidth: 38, halign: "right" },
      3: { cellWidth: 32, halign: "right" },
      5: { cellWidth: 30, halign: "right" },
    },
    margin: { left: 14, right: 14 },
  });

  drawFooter(doc);
  doc.save(`Shipments_${todayStr().replace(/\//g, "-")}.pdf`);
}

// ─── Excel – Shipments Tracker ────────────────────────────────────────────────

export function exportShipmentsExcel(shipments: Shipment[]) {
  const wb = XLSX.utils.book_new();
  const stages = ["تم الشراء", "في مستودع الصين", "في البحر / الجو", "التخليص الجمركي", "واصل للمستودع"];

  const summaryRows: any[][] = [
    ["Shipments Tracker Report  –  تقرير متابعة الشحنات"],
    ["Date:", todayStr(), "", "Total Shipments:", shipments.length],
    [],
    ["المرحلة / Stage", "عدد الشحنات"],
    ...stages.map(s => [s, shipments.filter(sh => sh.stage === s).length]),
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  wsSummary["!cols"] = [{ wch: 30 }, { wch: 15 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Stage Summary");

  const allRows: any[][] = [
    ["#", "اسم الشحنة", "المنتج", "المورد", "رقم الحاوية", "المرحلة الحالية",
     "تاريخ الإنشاء", "آخر تحديث", "عدد الملاحظات"],
    ...shipments.map((s, i) => [
      i + 1, s.name, s.productName, s.supplier,
      s.containerNumber || "—", s.stage,
      new Date(s.createdAt).toLocaleDateString("en-GB"),
      new Date(s.updatedAt).toLocaleDateString("en-GB"),
      s.notes.length,
    ]),
  ];
  const wsAll = XLSX.utils.aoa_to_sheet(allRows);
  wsAll["!cols"] = [{ wch: 5 }, { wch: 30 }, { wch: 25 }, { wch: 25 },
    { wch: 18 }, { wch: 20 }, { wch: 14 }, { wch: 14 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, wsAll, "All Shipments");

  const noteRows: any[][] = [
    ["Shipment Name", "Stage", "Date & Time", "Note Content"],
  ];
  shipments.forEach(s => {
    s.notes.forEach(n => {
      noteRows.push([s.name, s.stage, new Date(n.timestamp).toLocaleString("en-GB"), n.content]);
    });
  });
  const wsNotes = XLSX.utils.aoa_to_sheet(noteRows);
  wsNotes["!cols"] = [{ wch: 30 }, { wch: 20 }, { wch: 20 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, wsNotes, "Notes Log");

  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  triggerDownload(
    new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `Shipments_${todayStr().replace(/\//g, "-")}.xlsx`
  );
}
